# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy ASP.Net Core app to Azure Web App - MyMovie

#Trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
env:
  AZURE_WEBAPP_NAME: 'MyMovie'
  AZURE_WEBAPP_PACKAGE_PATH: './MyMovie'
  AZURE_PUBLISH_PROFILE: secrets.AzureAppService_PublishProfile_7182fc364c9e40b1ba0e112c909f597b
  DOTNET_VERSION: '3.1.301'
  
  # Add secrets to code
  #SECRET_IN_CODE: secrets.SECRET_FROM_GITHUB
  #SECRET_IN_CODE: secrets.SECRET_FROM_GITHUB
  #SECRET_IN_CODE: secrets.SECRET_FROM_GITHUB
  #SECRET_IN_CODE: secrets.SECRET_FROM_GITHUB

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: dotnet publish
        run: dotnet publish --no-build -c Release -o ${{ env.DOTNET_ROOT }}/myapp   #path to artifact folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:    
    runs-on: windows-latest
    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
